services:
  api:
    build:
      context: ./Prueba
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "5000:8080"
    networks:
      - mi_red

networks:
  mi_red:
    driver: bridge
